# PHP Web Server
web:
  environment:
    VIRTUAL_HOST: files.f5.wtf
  build: https://github.com/oleksandrakerman/vsftpd-docker.git#:build/f5-files-drupal
  volumes:
   - /opt/sites/files.f5.wtf/:/var/www/html
  volumes_from:
   - vsftpd
  links:
   - mysql
   - mysql_pam

# MySQL
mysql:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: s3cr3t
    MYSQL_USER: f5_files
    MYSQL_PASSWORD: f5_files
    MYSQL_DATABASE: f5_files
  volumes:
    - /opt/sites/files.f5.wtf/data/mysql:/var/lib/mysql

# MySQL pam
mysql_pam:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: s3cr3t
    MYSQL_USER: vsftpd
    MYSQL_PASSWORD: ftpdpass
    MYSQL_DATABASE: vsftpd
  volumes:
    - /opt/sites/files.f5.wtf/data/mysql_pam:/var/lib/mysql

# vsftpd+pam
vsftpd:
  build: https://github.com/oleksandrakerman/vsftpd-docker.git#:build/vsftpd
  ports:
   - "21:21"
   - "50000:50000"
   - "50001:50001"
   - "50002:50002"
   - "50003:50003"
   - "50004:50004"
   - "50005:50005"
  links:
   - mysql_pam

